previews:
  generation: disabled

# List all services *except* PostgreSQL databases here
services:
  # A Redis instance
  - type: redis
    name: lightning
    ipAllowList: # Required
      - source: 0.0.0.0/0
        description: everywhere
    plan: free # Default: starter
    maxmemoryPolicy: noeviction # Default: allkeys-lru

  # Linear Assistant
  - type: web
    name: linear-assistant
    env: node
    buildCommand: cd linear-assistant-ts && npm install && npm run build
    startCommand: cd linear-assistant-ts && npm start
    envVars:
      - fromGroup: agent-settings

  # DeployBot
  - type: web
    name: deploybot
    env: node
    buildCommand: cd deploybot-ts && npm install && npm run build
    startCommand: cd deploybot-ts && npm start
    envVars:
      - fromGroup: deploybot-settings
    port: 8001

# Environment groups
envVarGroups:
  - name: agent-settings
    envVars:
      - key: LINEAR_API_KEY
        value: ""
        description: "Linear API key for accessing Linear's API"
      - key: LOOPS_API_KEY
        value: ""
        description: "Loops API key for mailing list management"
      - key: REDIS_CACHE_URL
        value: "redis://lightning:6379/1"
        description: "Redis connection URL for caching"
      - key: STATE_MODE
        value: "remote"
        description: "State management mode (remote or cache)"
      - key: DEBUG
        value: "false"
        description: "Enable debug logging"
      - key: ALLOWED_SOURCE_EMAILS
        value: ""
        description: "Comma-separated list of allowed sender email addresses"
      - key: ALLOWED_TARGET_EMAILS
        value: ""
        description: "Comma-separated list of allowed recipient email addresses"
      - key: WEBHOOK_SIGNING_SECRET
        value: ""
        description: "Secret for verifying webhook signatures"
      - key: HUMANLAYER_API_KEY
        value: ""
        description: "API key for HumanLayer service"

  - name: deploybot-settings
    envVars:
      - key: GITHUB_TOKEN
        value: ""
        description: "GitHub API token for accessing GitHub's API"
      - key: GITHUB_OWNER
        value: ""
        description: "GitHub repository owner"
      - key: GITHUB_REPO
        value: ""
        description: "GitHub repository name"
      - key: VERCEL_TOKEN
        value: ""
        description: "Vercel API token for accessing Vercel's API"
      - key: VERCEL_PROJECT_ID
        value: ""
        description: "Vercel project ID"
      - key: VERCEL_TEAM_ID
        value: ""
        description: "Vercel team ID (optional)"
      - key: WEBHOOK_SIGNING_SECRET
        value: ""
        description: "Secret for verifying webhook signatures"
      - key: HUMANLAYER_API_KEY
        value: ""
        description: "API key for HumanLayer service"
      - key: REDIS_CACHE_URL
        value: "redis://lightning:6379/1"
        description: "Redis connection URL for caching"
      - key: DEFAULT_SLACK_CHANNEL
        value: ""
        description: "Default Slack channel ID for notifications"
