on:
  workflow_dispatch:
    inputs:
      type:
        description: 'The type of release (patch, minor, major)'
        required: false
        type: string
      semantic_version:
        description: 'The semantic version to release'
        required: false
        type: string
      triggered_by:
        description: 'Who triggered the workflow'
        required: false
        type: string
      environment:
        description: 'Target environment'
        required: false
        type: string
