name: Tag and Push to Production

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'The type of release (patch, minor, major)'
        required: false
        type: string
      semantic_version:
        description: 'The semantic version to release'
        required: false
        type: string
      triggered_by:
        description: 'Who triggered the workflow'
        required: false
        type: string
      environment:
        description: 'Target environment'
        required: false
        type: string

jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Check inputs
        run: |
          echo "Release Type: ${{ github.event.inputs.type }}"
          echo "Semantic Version: ${{ github.event.inputs.semantic_version }}"
          echo "Triggered By: ${{ github.event.inputs.triggered_by }}"
          echo "Environment: ${{ github.event.inputs.environment }}"

  build:
    runs-on: ubuntu-latest
    needs: validate-inputs
    steps:
      - name: Dummy Build Step
        run: echo "Building the application..."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Dummy Deploy Step
        run: echo "Deploying to ${{ github.event.inputs.environment }} environment..."
